# postgres-datasource.yaml
apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: logs
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 5
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false
